### ISSUE TITLE
Problem In Setting Up on Minikube

### ISSUE THREAD

**Issue by II-VSB-II** [gojek/merlin#168]
### Specifications
I was trying to set up locally following this doc: https://github.com/gojek/merlin/blob/main/docs/getting-started/deploying-merlin/local_development.md but not able to configure properly.  
With MERLIN_VERSION=v0.9.0 version pods are crashing in mlp name space but after changing version to v0.10.0 all pods are deploying. 
I am able to access merlin on http://merlin.mlp.127.0.0.1.nip.io/merlin and mlp on http://mlp.mlp.127.0.0.1.nip.io/merlin but only the first page, when I tried to authenticate error out redirect url mis match. As mention in docs we need to put Authorised JavaScript origins and Authorised redirect URIs in http but its only support https for this type (https://merlin.mlp.127.0.0.1.nip.io/merlin)  of urls.

- Version:
- Platform:
- Subsystem:

**Comment by ariefrahmansyah** [comment]
Hi @II-VSB-II. In our setup, we can use `http` in both Authorized JavaSciprt origins and redirect URIs. We created Oauth 2.0 Client ID with web application type. Please elaborate on how you create yours or any error message to help us troubleshoot.

**Comment by II-VSB-II** [comment]
<img width="451" alt="Screenshot 2021-08-10 at 9 10 01 AM" src="https://user-images.githubusercontent.com/18592412/128804873-233fc393-2155-465b-987e-67736e8a5ba2.png">
 
I also created for Web Application, I attached the screenshot if I am putting without https it now allowing me to save.

**Comment by ariefrahmansyah** [comment]
Seems like you have sensitive or restricted scopes on your OAuth consent screen. Please follow this link to try to solve the issue: https://stackoverflow.com/a/58385447

**Comment by ariefrahmansyah** [comment]
Hi @II-VSB-II. Do you manage to have Merlin working?

**Comment by ariefrahmansyah** [comment]
Closing stale issue.
